# Initialization

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import sklearn.datasets
# from init_utils import sigmoid, relu, compute_loss, forward_propagation, backward_propagation
# from init_utils import update_parameters, predict, load_dataset, plot_decision_boundary, predict_dec

%matplotlib inline
plt.rcParams['figure.figsize'] = (7.0, 4.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'


In [ ]:
def load_dataset():
    np.random.seed(1)
    train_X, train_Y = sklearn.datasets.make_circles(n_samples=300, noise=.05)
    np.random.seed(2)
    test_X, test_Y = sklearn.datasets.make_circles(n_samples=100, noise=.05)
    # Visualize the data
    plt.scatter(train_X[:, 0], train_X[:, 1], c=train_Y, s=40, cmap=plt.cm.Spectral);
    train_X = train_X.T
    train_Y = train_Y.reshape((1, train_Y.shape[0]))
    test_X = test_X.T
    test_Y = test_Y.reshape((1, test_Y.shape[0]))
    return train_X, train_Y, test_X, test_Y

In [ ]:
# load image dataset: blue/red dots in circles
train_X, train_Y, test_X, test_Y = load_dataset()

# 1 - 신경망 모델

당신은 3-레이어 신경망을 사용할 것입니다 (이미 구현되어 있음). 다음은 실험하게 될 초기화 방법들입니다:

- **Zeros 초기화** — 입력 인자에서 `initialization = "zeros"`로 설정합니다.
- **Random 초기화** — 입력 인자에서 `initialization = "random"`로 설정합니다. 이 방법은 가중치를 큰 랜덤 값으로 초기화합니다.
- **He 초기화** — 입력 인자에서 `initialization = "he"`로 설정합니다. 이 방법은 2015년 He 외 논문에 따라 가중치를 스케일된 랜덤 값으로 초기화합니다.

**지침:** 아래 코드를 빠르게 읽고 실행해보세요. 다음 파트에서는 이 `model()` 함수에서 호출하는 세 가지 초기화 방법을 구현하게 됩니다.

In [ ]:

# def model(X, Y, learning_rate=0.01, num_iterations=15000, print_cost=True, initialization="he"):
#     """
#     Implements a three-layer neural network: LINEAR->RELU->LINEAR->RELU->LINEAR->SIGMOID.
    
#     Arguments:
#     X -- input data, of shape (2, number of examples)
#     Y -- true "label" vector (containing 0 for red dots; 1 for blue dots), of shape (1, number of examples)
#     learning_rate -- learning rate for gradient descent 
#     num_iterations -- number of iterations to run gradient descent
#     print_cost -- if True, print the cost every 1000 iterations
#     initialization -- flag to choose which initialization to use ("zeros","random" or "he")
    
#     Returns:
#     parameters -- parameters learnt by the model
#     """
        
#     costs = [] # to keep track of the loss
#     layers_dims = [X.shape[0], 10, 5, 1]
#     last_L = len(layers_dims)-1
    
#     parameters = initialize_parameters(layers_dims,initialization)
    
#     for i in range(0, num_iterations):

#         # Forward propagation: LINEAR -> RELU -> LINEAR -> RELU -> LINEAR -> SIGMOID.
#         cache = forward_propagation(X, parameters)
#         a = cache['A'+str(last_L)]
        
#         # Loss
#         cost = compute_loss(a, Y)

#         # Backward propagation and update parameters.
#         parameters = backward_propagation_update(a, Y, cache,learning_rate)
        
#         # Print the loss every 1000 iterations
#         if print_cost and i % 1000 == 0:
#             print("Cost after iteration {}: {}".format(i, cost))
#             costs.append(cost)
            
#     # plot the loss
#     plt.plot(costs)
#     plt.ylabel('cost')
#     plt.xlabel('iterations (per hundreds)')
#     plt.title("Learning rate =" + str(learning_rate))
#     plt.show()
    
#     return parameters

In [ ]:
# from re_utils import forward_propagation_for_predict
# def predict(X, y, parameters):
#     """
#     This function is used to predict the results of a  n-layer neural network.
    
#     Arguments:
#     X -- data set of examples you would like to label
#     parameters -- parameters of the trained model
    
#     Returns:
#     p -- predictions for the given dataset X
#     """
    
#     m = X.shape[1]
#     p = np.zeros((1,m), dtype = np.int)     # 저장할 파라미터
    
#     # Forward propagation
#     aL = forward_propagation_for_predict(X, parameters)
    
#     # convert probas to 0/1 predictions
#     for i in range(0, aL.shape[1]):
#         if aL[0,i] > 0.5:
#             p[0,i] = 1
#         else:
#             p[0,i] = 0

#     # print results
#     print("Accuracy: "  + str(np.mean((p[0,:] == y[0,:]))))
    
#     return p

In [ ]:
from re_utils import compute_loss, forward_propagation, backward_propagation_update,initialize_parameters,forward_propagation_for_predict, predict_re, model_re

## 2 - Zero 초기화

신경망에서 초기화해야 할 파라미터는 두 가지 종류가 있습니다:
- 가중치 행렬 $(W^{[1]}, W^{[2]}, W^{[3]}, ..., W^{[L-1]}, W^{[L]})$
- 편향 벡터 $(b^{[1]}, b^{[2]}, b^{[3]}, ..., b^{[L-1]}, b^{[L]})$

**연습 문제**: 모든 파라미터를 0으로 초기화하는 다음 함수를 구현해보세요.  
나중에 보게 되겠지만, 이렇게 하면 "대칭성을 깨지 못하기 때문에" 잘 작동하지 않습니다.  
하지만 일단 시도해보고 어떤 일이 일어나는지 확인해봅시다.  
`np.zeros((..,..))`를 사용하되, 올바른 형태(shape)를 사용하세요.

In [ ]:
parameters = initialize_parameters([3,2,1],'zeros')
print("W1 = " + str(parameters["W1"]))
print("b1 = " + str(parameters["b1"]))
print("W2 = " + str(parameters["W2"]))
print("b2 = " + str(parameters["b2"]))

Run the following code to train your model on 15,000 iterations using zeros initialization.

In [ ]:
parameters = model_re(train_X, train_Y, initialization = "zeros")
print ("On the train set:")
predictions_train = predict_re(train_X, train_Y, parameters)
print ("On the test set:")
predictions_test = predict_re(test_X, test_Y, parameters)

여기까지
---

In [ ]:
parameters = model(train_X, train_Y, initialization = "zeros")
print ("On the train set:")
predictions_train = predict(train_X, train_Y, parameters)
print ("On the test set:")
predictions_test = predict(test_X, test_Y, parameters)

The performance is really bad, and the cost does not really decrease, and the algorithm performs no better than random guessing. Why? Lets look at the details of the predictions and the decision boundary:

In [ ]:
print("predictions_train = " + str(predictions_train))
print("predictions_test = " + str(predictions_test))

In [ ]:
plt.title("Model with Zeros initialization")
axes = plt.gca()
axes.set_xlim([-1.5, 1.5])
axes.set_ylim([-1.5, 1.5])
plot_decision_boundary(lambda x: predict_dec(parameters, x.T), train_X, train_Y)

모델이 모든 예제에 대해 0만 예측하고 있습니다.

일반적으로, 모든 가중치를 0으로 초기화하면 네트워크가 대칭성을 깨는 데 실패하게 됩니다.  
이는 각 층의 모든 뉴런이 동일한 것을 학습하게 된다는 것을 의미하며,  
결국 각 층에서 $n^{[l]}=1$인 신경망을 학습하는 것과 다를 바 없게 됩니다.  
이러한 경우, 신경망은 로지스틱 회귀와 같은 선형 분류기보다 더 강력하지 않게 됩니다.

<font color='blue'>

**기억해야 할 것**:
- 가중치 $W^{[l]}$는 대칭성을 깨기 위해 랜덤하게 초기화되어야 합니다.  
- 하지만 편향 $b^{[l]}$는 0으로 초기화해도 괜찮습니다.  
  $W^{[l]}$만 랜덤하게 초기화된다면, 대칭성은 여전히 깨지기 때문입니다.

## 3 - Random 초기화

대칭성을 깨기 위해, 가중치를 랜덤하게 초기화해봅시다.  
랜덤 초기화를 통해 각 뉴런은 입력에 대해 서로 다른 함수를 학습할 수 있게 됩니다.  
이번 연습에서는, 가중치를 매우 큰 값으로 랜덤하게 초기화했을 때 어떤 일이 일어나는지 확인하게 됩니다.

**연습 문제**: 다음 함수를 구현하여 가중치를 큰 랜덤 값(10배 스케일링)으로 초기화하고, 편향은 0으로 초기화하세요.  
가중치에는 `np.random.randn(.., ..) * 10`을, 편향에는 `np.zeros((.., ..))`을 사용하세요.  
우리는 `np.random.seed(..)`를 고정하여 "랜덤한" 가중치가 항상 동일하게 생성되도록 했습니다.  
따라서 여러 번 실행해도 초기 파라미터 값이 항상 같더라도 걱정하지 마세요.

In [ ]:
# GRADED FUNCTION: initialize_parameters_random

def initialize_parameters_random(layers_dims):
    """
    Arguments:
    layer_dims -- python array (list) containing the size of each layer.
    
    Returns:
    parameters -- python dictionary containing your parameters "W1", "b1", ..., "WL", "bL":
                    W1 -- weight matrix of shape (layers_dims[1], layers_dims[0])
                    b1 -- bias vector of shape (layers_dims[1], 1)
                    ...
                    WL -- weight matrix of shape (layers_dims[L], layers_dims[L-1])
                    bL -- bias vector of shape (layers_dims[L], 1)
    """
    
    np.random.seed(3)               # This seed makes sure your "random" numbers will be the as ours
    parameters = {}
    L = len(layers_dims)            # integer representing the number of layers
    
    for l in range(1, L):
        ### START CODE HERE ### (≈ 2 lines of code)
        parameters['W' + str(l)] = np.random.randn(layers_dims[l], layers_dims[l - 1]) * 10
        parameters['b' + str(l)] = np.zeros((layers_dims[l], 1))
        ### END CODE HERE ###

    return parameters

In [ ]:
parameters = initialize_parameters_random([3, 2, 1])
print("W1 = " + str(parameters["W1"]))
print("b1 = " + str(parameters["b1"]))
print("W2 = " + str(parameters["W2"]))
print("b2 = " + str(parameters["b2"]))

**Expected Output**:

<table> 
    <tr>
    <td>
    **W1**
    </td>
        <td>
    [[ 17.88628473   4.36509851   0.96497468]
 [-18.63492703  -2.77388203  -3.54758979]]
    </td>
    </tr>
    <tr>
    <td>
    **b1**
    </td>
        <td>
    [[ 0.]
 [ 0.]]
    </td>
    </tr>
    <tr>
    <td>
    **W2**
    </td>
        <td>
    [[-0.82741481 -6.27000677]]
    </td>
    </tr>
    <tr>
    <td>
    **b2**
    </td>
        <td>
    [[ 0.]]
    </td>
    </tr>

</table> 

Run the following code to train your model on 15,000 iterations using random initialization.

In [ ]:
parameters = model(train_X, train_Y, initialization = "random")
print("On the train set:")
predictions_train = predict(train_X, train_Y, parameters)
print("On the test set:")
predictions_test = predict(test_X, test_Y, parameters)

iteration 0 이후에 비용(cost)이 "inf"로 표시된다면,  
이는 수치적인 반올림 오차(numerical roundoff) 때문입니다.  
좀 더 정교한 수치 해석 구현이라면 이를 해결할 수 있겠지만,  
우리의 목적에서는 굳이 걱정할 필요는 없습니다.

어쨌든, 대칭성은 깨졌고, 이전보다 더 나은 결과를 보여주고 있습니다.  
모델이 더 이상 모든 예제에 대해 0만 출력하지 않습니다.

In [ ]:
print(predictions_train)
print(predictions_test)

In [ ]:
plt.title("Model with large random initialization")
axes = plt.gca()
axes.set_xlim([-1.5, 1.5])
axes.set_ylim([-1.5, 1.5])
plot_decision_boundary(lambda x: predict_dec(parameters, x.T), train_X, train_Y)

**관찰 결과**:
- 비용(cost)이 매우 높은 값에서 시작합니다.  
  이는 가중치가 큰 랜덤 값으로 초기화되었기 때문인데,  
  이 경우 마지막 활성화 함수(sigmoid)가 일부 예제에 대해 0 또는 1에 매우 가까운 값을 출력하게 됩니다.  
  이때 예측이 틀리면 해당 예제에 대해 매우 큰 손실(loss)이 발생하게 됩니다.  
  실제로 $\log(a^{[3]}) = \log(0)$일 경우, 손실은 무한대로 발산합니다.
  
- 잘못된 초기화는 **그래디언트 소실/폭발(vanishing/exploding gradients)**을 일으킬 수 있으며,  
  이는 최적화 알고리즘을 느리게 만듭니다.

- 이 네트워크를 더 오래 학습시키면 더 나은 결과를 얻을 수는 있지만,  
  지나치게 큰 랜덤 수로 초기화하는 것은 최적화를 느리게 만듭니다.

<font color='blue'>

**요약**:
- 가중치를 매우 큰 랜덤 값으로 초기화하는 것은 좋지 않습니다.
- 작은 랜덤 값으로 초기화하면 더 나을 수 있습니다.  
  여기서 중요한 질문은: *이 랜덤 값들은 얼마나 작아야 할까?*  
  다음 파트에서 알아봅시다!

## 4 - He 초기화

마지막으로, **He 초기화**를 시도해봅시다.  
이 방법은 2015년 He 외 연구의 제1저자 이름을 따서 명명되었습니다.  
("Xavier 초기화"를 들어본 적이 있다면, 이와 비슷한 방식입니다.  
단, Xavier 초기화는 가중치 $W^{[l]}$에 `sqrt(1./layers_dims[l-1])` 스케일링을 사용하는 반면,  
He 초기화는 `sqrt(2./layers_dims[l-1])`을 사용합니다.)

**연습 문제**: 다음 함수를 구현하여 He 초기화를 이용해 파라미터를 초기화하세요.

**힌트**: 이 함수는 이전에 만들었던 `initialize_parameters_random(...)` 함수와 거의 유사합니다.  
차이점은 `np.random.randn(.., ..)`에 10을 곱하는 대신,  
이전 층의 크기를 기반으로 한 $\sqrt{\frac{2}{\text{이전 층의 차원}}}$을 곱한다는 점입니다.  
이는 ReLU 활성화 함수를 사용하는 층에 대해 He 초기화에서 권장하는 방식입니다.

In [ ]:
# GRADED FUNCTION: initialize_parameters_he

def initialize_parameters_he(layers_dims):
    """
    Arguments:
    layer_dims -- python array (list) containing the size of each layer.
    
    Returns:
    parameters -- python dictionary containing your parameters "W1", "b1", ..., "WL", "bL":
                    W1 -- weight matrix of shape (layers_dims[1], layers_dims[0])
                    b1 -- bias vector of shape (layers_dims[1], 1)
                    ...
                    WL -- weight matrix of shape (layers_dims[L], layers_dims[L-1])
                    bL -- bias vector of shape (layers_dims[L], 1)
    """
    
    np.random.seed(3)
    parameters = {}
    L = len(layers_dims) - 1 # integer representing the number of layers
     
    for l in range(1, L + 1):
        ### START CODE HERE ### (≈ 2 lines of code)
        parameters['W' + str(l)] = np.random.randn(layers_dims[l], layers_dims[l - 1]) * np.sqrt(2 / layers_dims[l - 1])
        parameters['b' + str(l)] = np.zeros((layers_dims[l], 1))
        ### END CODE HERE ###
        
    return parameters

In [ ]:
parameters = initialize_parameters_he([2, 4, 1])
print("W1 = " + str(parameters["W1"]))
print("b1 = " + str(parameters["b1"]))
print("W2 = " + str(parameters["W2"]))
print("b2 = " + str(parameters["b2"]))

**Expected Output**:

<table> 
    <tr>
    <td>
    **W1**
    </td>
        <td>
    [[ 1.78862847  0.43650985]
 [ 0.09649747 -1.8634927 ]
 [-0.2773882  -0.35475898]
 [-0.08274148 -0.62700068]]
    </td>
    </tr>
    <tr>
    <td>
    **b1**
    </td>
        <td>
    [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]
    </td>
    </tr>
    <tr>
    <td>
    **W2**
    </td>
        <td>
    [[-0.03098412 -0.33744411 -0.92904268  0.62552248]]
    </td>
    </tr>
    <tr>
    <td>
    **b2**
    </td>
        <td>
    [[ 0.]]
    </td>
    </tr>

</table> 

Run the following code to train your model on 15,000 iterations using He initialization.

In [ ]:
parameters = model(train_X, train_Y, initialization = "he")
print("On the train set:")
predictions_train = predict(train_X, train_Y, parameters)
print("On the test set:")
predictions_test = predict(test_X, test_Y, parameters)

In [ ]:
plt.title("Model with He initialization")
axes = plt.gca()
axes.set_xlim([-1.5, 1.5])
axes.set_ylim([-1.5, 1.5])
plot_decision_boundary(lambda x: predict_dec(parameters, x.T), train_X, train_Y)

**Observations**:
- The model with He initialization separates the blue and the red dots very well in a small number of iterations.


## 5 - Conclusions

You have seen three different types of initializations. For the same number of iterations and same hyperparameters the comparison is:

<table> 
    <tr>
        <td>
        **Model**
        </td>
        <td>
        **Train accuracy**
        </td>
        <td>
        **Problem/Comment**
        </td>

    </tr>
        <td>
        3-layer NN with zeros initialization
        </td>
        <td>
        50%
        </td>
        <td>
        fails to break symmetry
        </td>
    <tr>
        <td>
        3-layer NN with large random initialization
        </td>
        <td>
        83%
        </td>
        <td>
        too large weights 
        </td>
    </tr>
    <tr>
        <td>
        3-layer NN with He initialization
        </td>
        <td>
        99%
        </td>
        <td>
        recommended method
        </td>
    </tr>
</table> 

<font color='blue'>

**이 노트북에서 기억해야 할 것**:
- 초기화 방식에 따라 결과가 달라질 수 있습니다.
- 랜덤 초기화는 대칭성을 깨고, 서로 다른 은닉 유닛들이 서로 다른 것을 학습할 수 있도록 도와줍니다.
- 너무 큰 값으로 초기화하지 마세요.
- He 초기화는 ReLU 활성화 함수를 사용하는 네트워크에서 좋은 성능을 보입니다.